import {LearningError} from './learning';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'private, no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff'}})}
export async function user(request?:Request){const u=await getChatGPTUser();if(!u)throw new ApiError('Sign in with ChatGPT to save and sync your library.',401);if(request?.headers.has('x-genbooks-account')&&request.headers.get('x-genbooks-account')!==u.userId)throw new ApiError('This browser changed accounts. Reload GenBooks before saving; copy any unsaved draft first.',409);return u.userId;}
export class ApiError extends Error{constructor(message:string,public status=400){super(message)}}
export async function input(request:Request,maxBytes=250000){const origin=request.headers.get('origin');if(!origin||origin!==new URL(request.url).origin||request.headers.get('sec-fetch-site')==='cross-site')throw new ApiError('This save must come from GenBooks in your browser.',403);if(!request.headers.get('content-type')?.startsWith('application/json'))throw new ApiError('Send JSON data.',415);const reader=request.body?.getReader();if(!reader)throw new ApiError('Missing request.');let size=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes){await reader.cancel();throw new ApiError('This item is too large. Use a smaller text or EPUB file.',413);}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.byteLength;}try{return JSON.parse(new TextDecoder().decode(bytes))}catch{throw new ApiError('The request could not be read.');}}
export function failure(e:unknown){if(e instanceof LearningError)return json({error:e.message},409);if(e instanceof ApiError)return json({error:e.message},e.status);console.error('GenBooks operation failed',e instanceof Error?e.name:'UnknownError');return json({error:'Saving is temporarily unavailable. Your input is still here; try again.'},503)}
export function id(value:unknown):string{if(typeof value!=='string'||['__proto__','constructor','prototype'].includes(value)||!/^[a-zA-Z0-9_-]{1,100}$/.test(value))throw new ApiError('Invalid item identifier.');return value;}
export function text(value:unknown,max:number,allowEmpty=false):string{if(typeof value!=='string'||value.length>max||(!allowEmpty&&!value.trim()))throw new ApiError('Please enter valid text within the displayed limit.');return value.trim();}
