import {Unzip,UnzipInflate,strFromU8} from 'fflate';
export type ImportDraft={title:string;author:string;chapters:{title:string;blocks:{kind:string;text:string}[]}[]};
function clean(value:string){return value.replace(/\u0000/g,'').replace(/[ \t]+/g,' ').trim()}
function paragraphs(text:string){return text.split(/\n\s*\n/).map(clean).filter(Boolean).flatMap(t=>{const parts=[];for(let at=0;at<t.length;at+=25000)parts.push({kind:'paragraph',text:t.slice(at,at+25000)});return parts})}
function safePath(base:string,href:string){const u=new URL(href,'https://epub.local/'+base);if(u.origin!=='https://epub.local')throw Error('This EPUB links to external content instead of including its chapters.');return decodeURIComponent(u.pathname.slice(1));}
export async function parseBook(file:File):Promise<ImportDraft>{
 if(file.size>8*1024*1024)throw Error('Choose a file smaller than 8 MB. Extracted text can be up to 1.5 MB.');
 if(!/\.epub$/i.test(file.name)){if(!/\.(txt|md)$/i.test(file.name))throw Error('Choose a DRM-free EPUB, plain text (.txt), or Markdown (.md) file.');const text=await file.text();const blocks=paragraphs(text);if(!blocks.length)throw Error('This file has no readable text.');return {title:file.name.replace(/\.[^.]+$/,''),author:'Imported by you',chapters:Array.from({length:Math.ceil(blocks.length/500)},(_,i)=>({title:blocks.length>500?'Part '+(i+1):'Reading',blocks:blocks.slice(i*500,(i+1)*500)}))};}
 const bytes=new Uint8Array(await file.arrayBuffer());const entries=new Map<string,Uint8Array>();let expanded=0;let count=0;let error:Error|undefined;
 const unzip=new Unzip(entry=>{count++;if(count>2000){error=Error('This EPUB contains too many files.');return;}if(!/\.(xhtml|html|htm|xml|opf)$/i.test(entry.name))return;const parts:Uint8Array[]=[];let size=0;entry.ondata=(err,data,final)=>{if(err){error=err;return;}size+=data.length;expanded+=data.length;if(size>2_000_000||expanded>8_000_000){entry.terminate();error=Error('This EPUB expands beyond the 8 MB text-reading limit.');return;}parts.push(data);if(final){const out=new Uint8Array(size);let at=0;for(const p of parts){out.set(p,at);at+=p.length;}entries.set(entry.name,out);}};entry.start();});unzip.register(UnzipInflate);
 for(let at=0;at<bytes.length;at+=8192){if(error)throw error;unzip.push(bytes.subarray(at,at+8192),at+8192>=bytes.length);}if(error)throw error;
 const xml=(path:string)=>{const b=entries.get(path);if(!b)throw Error('This EPUB is missing '+path+'. It may be protected or incomplete.');const doc=new DOMParser().parseFromString(strFromU8(b),'application/xml');if(doc.querySelector('parsererror'))throw Error('The EPUB package could not be read.');return doc;};
 if(entries.has('META-INF/encryption.xml'))throw Error('This EPUB declares encrypted content. Import a DRM-free copy or plain text.');
 const container=xml('META-INF/container.xml');const opf=container.getElementsByTagNameNS('*','rootfile')[0]?.getAttribute('full-path');if(!opf)throw Error('The EPUB has no book package.');const pkg=xml(opf);const title=clean(pkg.getElementsByTagNameNS('*','title')[0]?.textContent||file.name);const author=clean(pkg.getElementsByTagNameNS('*','creator')[0]?.textContent||'Imported by you');const items=new Map(Array.from(pkg.getElementsByTagNameNS('*','item')).map(e=>[e.getAttribute('id'),e.getAttribute('href')]));const spine=Array.from(pkg.getElementsByTagNameNS('*','itemref')).filter(e=>e.getAttribute('linear')!=='no');if(spine.length>100)throw Error('Import a book with up to 100 chapters.');
 const chapters=spine.flatMap((e,i)=>{const href=items.get(e.getAttribute('idref'));if(!href)return [];const path=safePath(opf,href);const data=entries.get(path);if(!data)throw Error('One of the EPUB chapters is missing.');const doc=new DOMParser().parseFromString(strFromU8(data),'text/html');doc.querySelectorAll('script,style,noscript,nav,iframe,object,svg').forEach(e=>e.remove());const chapterTitle=clean(doc.querySelector('h1,h2,title')?.textContent||'Chapter '+(i+1));let blocks=Array.from(doc.querySelectorAll('p,h1,h2,h3,blockquote,li')).filter(e=>!e.parentElement?.closest('p,blockquote,li')).map(e=>({kind:/^H/.test(e.tagName)?'heading':'paragraph',text:clean(e.textContent||'')})).filter(b=>b.text);if(!blocks.length)blocks=paragraphs(doc.body.textContent||'');if(blocks.some(b=>b.text.length>30000)||blocks.length>1000)throw Error('A chapter is too large; import a shorter section.');return blocks.length?[{title:chapterTitle,blocks}]:[];});
 if(!chapters.length)throw Error('No readable text was found in this EPUB.');const result={title,author,chapters};if(new TextEncoder().encode(JSON.stringify(result)).length>1_400_000)throw Error('Extracted text exceeds 1.5 MB. Import a shorter section.');return result;
}
