import {ApiError} from './api';
import {env} from 'cloudflare:workers';
import {freshLearning,validateLearning} from './learning';
import {validRecords,type AppState} from './models';
export function freshState():AppState{return {schema:1,learning:freshLearning(),books:[],positions:{},notes:[],mutationIds:[],preferences:{sessionMinutes:10}}}
function db(){if(!env.DB)throw new ApiError('Account storage is temporarily unavailable. Your existing data has not been replaced.');return env.DB;}
export async function loadState(user:string){const row=await db().prepare('SELECT payload, revision FROM genbooks_accounts WHERE user_id = ?').bind(user).first<{payload:string;revision:number}>();if(!row)return {state:freshState(),revision:0,exists:false};let state:AppState;try{state=JSON.parse(row.payload);if(state.schema!==1||!Array.isArray(state.notes)||!Array.isArray(state.books)||!Array.isArray(state.mutationIds)||!state.positions||!state.preferences||!validRecords(state)||!validateLearning(state.learning))throw new ApiError("Unreadable account data.");}catch{throw new ApiError('Your saved data could not be read. It has been preserved; contact support before continuing.');}return {state,revision:row.revision,exists:true};}
export async function mutateState<T>(user:string,fn:(state:AppState)=>T){for(let tries=0;tries<4;tries++){const {state,revision,exists}=await loadState(user);const result=fn(state);const payload=JSON.stringify(state);if(new TextEncoder().encode(payload).length>1_500_000)throw new ApiError('Your account has reached the current learning-record storage limit. Export your data from Settings; no existing records were removed.');let write;if(exists)write=await db().prepare('UPDATE genbooks_accounts SET payload = ?, revision = revision + 1, updated_at = ? WHERE user_id = ? AND revision = ?').bind(payload,Date.now(),user,revision).run();else write=await db().prepare('INSERT OR IGNORE INTO genbooks_accounts (user_id, payload, revision, updated_at) VALUES (?, ?, 1, ?)').bind(user,payload,Date.now()).run();if(write.meta.changes===1)return {state,revision:revision+1,result};}throw new ApiError('Another browser saved at the same moment. Your input is still here; try saving again.');}
export function bucket(){if(!env.BUCKET)throw new ApiError('Book storage is temporarily unavailable.');return env.BUCKET;}

export async function ownedBookObject(owner:string,key:string){const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(owner)))).map(b=>b.toString(16).padStart(2,'0')).join('');if(!key.startsWith(`books/${digest}/`))throw new ApiError('Book storage could not be verified.',503);const object=await bucket().get(key);if(!object)throw new ApiError('Book content is temporarily unavailable.',503);return object;}
