"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {BookOpen,Library,NotebookPen,ChevronLeft,ChevronRight,FlaskConical,Settings2,Plus,Search,Check,Cloud,CloudOff,Sun,Moon,Text,Bookmark,Download,Trash2,LoaderCircle,X,BookMarked,CheckCircle2,Clock3,Info,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {course,books,questions} from '@/lib/catalog';
import foundations from '@/content/foundations.json';
import {freshLearning,summary,reviewDue,type Presentation,type Receipt,type Question} from '@/lib/learning';
import type {AppState,Book,Note} from '@/lib/models';
import {parseBook,type ImportDraft} from '@/lib/import-book';
const empty=():AppState=>({schema:1,learning:freshLearning(),books:[],positions:{},notes:[],mutationIds:[],preferences:{sessionMinutes:10}});
const uid=()=>crypto.randomUUID();
const date=(ms:number)=>new Date(ms).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const dateTime=(ms:number)=>new Date(ms).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const cover=(kind:string)=>'/covers/'+(kind==='sample'?'argentina':kind==='physics'?'physics':'imported')+'.png';
function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={wide?'app-dialog wide':'app-dialog'}><DialogHeader><DialogTitle>{title}</DialogTitle>{description&&<DialogDescription>{description}</DialogDescription>}</DialogHeader>{children}</DialogContent></Dialog>}
function Action({children,onClick,primary=false,disabled=false,className='',type='button'}:{children:React.ReactNode;onClick?:()=>void;primary?:boolean;disabled?:boolean;className?:string;type?:'button'|'submit'}){return <button type={type} disabled={disabled} className={'action '+(primary?'primary ':'')+className} onClick={onClick}>{children}</button>}
type View={book:Book;chapter:number;restore?:string};
type Practice={question:Question;presentation?:Presentation;receipt?:Receipt;choice:string;help:boolean;explanation:boolean};
type Draft=Pick<Note,'id'|'bookId'|'bookTitle'|'chapter'|'chapterTitle'|'block'|'quote'|'body'|'kind'|'known'|'version'>;
export default function GenBooks({user,signIn,signOut}:{user:{name:string;scope:string}|null;signIn:string;signOut:string}){
 const [state,setState]=useState<AppState>(empty),[loaded,setLoaded]=useState(!user),[busy,setBusy]=useState(false),[error,setError]=useState(''),[synced,setSynced]=useState<number|null>(null),[now,setNow]=useState(Date.now());
 const stateRef=useRef(state),queue=useRef<Promise<unknown>>(Promise.resolve()),mounted=useRef(true),viewRef=useRef<View|null>(null),lastAnchor=useRef(''),revision=useRef(-1);
 const [tab,setTab]=useState('library'),[view,setView]=useState<View|null>(null),[settings,setSettings]=useState(false),[foundation,setFoundation]=useState<string|null>(null),[toc,setToc]=useState(false),[scoreOpen,setScoreOpen]=useState(false),[sources,setSources]=useState(false),[importOpen,setImportOpen]=useState(false),[importing,setImporting]=useState(false),[importDraft,setImportDraft]=useState<ImportDraft|null>(null),[importId,setImportId]=useState(''),[importError,setImportError]=useState(''),[practice,setPractice]=useState<Practice|null>(null),[noteDraft,setNoteDraft]=useState<Draft|null>(null),[deleteNote,setDeleteNote]=useState<Note|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[theme,setTheme]=useState('dark'),[fontSize,setFontSize]=useState(21),[finish,setFinish]=useState<string|null>(null);
 const update=useCallback((next:AppState)=>{stateRef.current=next;setState(next)},[]);
 const accept=useCallback((data:{state:AppState;serverTime?:number;revision:number;account:string})=>{if(data.account!==user?.scope)throw Error('This browser changed accounts. Reload GenBooks; copy any unsaved draft first.');if(!Number.isSafeInteger(data.revision))throw Error('The save confirmation is incomplete. Refresh before continuing.');if(data.revision<revision.current)return;revision.current=data.revision;update(data.state);setLoaded(true);setSynced(Date.now());if(data.serverTime)setNow(data.serverTime)},[update,user]);
 const refresh=useCallback(async()=>{if(!user)return;try{const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json() as any;if(!r.ok)throw Error(d.error);if(mounted.current){accept(d);setError('')}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Your saved library is temporarily unavailable.')}},[user,accept]);
 useEffect(()=>{mounted.current=true;void refresh();const onFocus=()=>{void queue.current.then(()=>refresh())};window.addEventListener('focus',onFocus);const timer=setInterval(()=>{if(document.visibilityState==='visible')onFocus()},30000);try{const saved=localStorage.getItem('genbooks-appearance');if(saved){const v=JSON.parse(saved);if(['light','dark'].includes(v.theme))setTheme(v.theme);if(v.font>=18&&v.font<=30)setFontSize(v.font)}}catch{}return()=>{mounted.current=false;window.removeEventListener('focus',onFocus);clearInterval(timer)}},[refresh]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('genbooks-appearance',JSON.stringify({theme,font:fontSize}))}catch{}},[theme,fontSize]);
 const mutate=useCallback(async(type:string,data:Record<string,unknown>={},requestId=uid()):Promise<any>=>{if(!user)throw Error('Sign in to save your progress.');const run=async()=>{setBusy(true);try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json','X-GenBooks-Account':user?.scope??''},body:JSON.stringify({...data,type,id:requestId})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);accept(d);setError('');return d.result}finally{setBusy(false)}};const next=queue.current.catch(()=>{}).then(run);queue.current=next;return next},[user,accept]);
 const attempt=useCallback(async(fn:()=>Promise<unknown>)=>{try{await fn()}catch(e){setError(e instanceof Error?e.message:'The change could not be saved. Your input is still here.')}},[]);
 const openBook=useCallback(async(bookOrId:Book|string,chapter?:number,anchor?:string)=>{try{let b:Book|undefined=typeof bookOrId==='string'?books.find(b=>b.id===bookOrId):bookOrId;if(!b&&typeof bookOrId==='string'){if(!user){window.location.assign(signIn);return false;}const r=await fetch('/api/books/'+encodeURIComponent(bookOrId),{cache:'no-store',headers:{'X-GenBooks-Account':user.scope}});const d=await r.json() as any;if(!r.ok)throw Error(d.error);b=d;}if(!b)throw Error('Book not found.');const pos=stateRef.current.positions[b.id];const index=Math.max(0,Math.min(chapter??pos?.chapter??0,b.chapters.length-1));const restore=anchor??(chapter===undefined||chapter===pos?.chapter?pos?.block:undefined);
 if(user&&b.kind==='physics')await mutate('lesson',{lesson:b.chapters[index].lessonId});
 const next={book:b,chapter:index,restore};viewRef.current=next;setView(next);setToc(false);setFinish(null);lastAnchor.current='';window.history.replaceState({},'',`/?book=${encodeURIComponent(b.id)}&chapter=${index}`);window.scrollTo({top:0});if(user)await mutate('position',{bookId:b.id,chapter:index,block:restore??''});return true;
 }catch(e){setError(e instanceof Error?e.message:'This book could not be opened.');return false;}},[user,mutate,signIn]);
 const initialOpened=useRef(false);useEffect(()=>{if(!loaded||initialOpened.current)return;initialOpened.current=true;const params=new URLSearchParams(window.location.search);const b=params.get('book');if(b){const n=Number(params.get('chapter')??0);void openBook(b,Number.isFinite(n)?n:0)}},[loaded,openBook]);
 useEffect(()=>{if(!view)return;let restoreTimer=window.setTimeout(()=>{if(view.restore){document.getElementById('block-'+view.restore)?.scrollIntoView({block:'start'});lastAnchor.current=view.restore}},100);let timer:number|undefined;const save=()=>{clearTimeout(timer);timer=window.setTimeout(()=>{const nodes=Array.from(document.querySelectorAll<HTMLElement>('[data-reading-block]'));const node=nodes.find(n=>n.getBoundingClientRect().bottom>120);const block=node?.dataset.readingBlock;if(!block||block===lastAnchor.current||!user)return;lastAnchor.current=block;void attempt(()=>mutate('position',{bookId:view.book.id,chapter:view.chapter,block}));},900)};window.addEventListener('scroll',save,{passive:true});return()=>{clearTimeout(restoreTimer);clearTimeout(timer);window.removeEventListener('scroll',save)}},[view,user,mutate,attempt]);
 const closeReader=()=>{viewRef.current=null;setView(null);setFinish(null);window.history.replaceState({},'','/');window.scrollTo({top:0})};
 const startPractice=async(concept:string,question?:string,review=true)=>{try{if(!user){const q=questions.find(q=>q.id===question)??questions.find(q=>q.conceptId===concept)!;setPractice({question:q,choice:'',help:false,explanation:false});return;}const p=await mutate('present',{concept,question,review});const q=questions.find(q=>q.id===p.question)!;setPractice({question:q,presentation:p,choice:'',help:false,explanation:false});}catch(e){setError(e instanceof Error?e.message:'Could not start this question.')}};
 const saveAnswer=async()=>{if(!practice||!practice.choice)return;try{if(practice.presentation){const r=await mutate('answer',{presentation:practice.presentation.id,choice:practice.choice,helped:practice.help});setPractice({...practice,receipt:r,explanation:true});}else{setPractice({...practice,receipt:{id:'preview',concept:practice.question.conceptId,question:practice.question.id,at:Date.now(),version:'physics-foundations-v1',correct:practice.choice===practice.question.correctChoiceId,helped:practice.help,counted:false,delta:0,reason:'Preview only. Sign in to save answer evidence and use the check score.',choice:practice.choice,review:false},explanation:true})}}catch(e){setError(e instanceof Error?e.message:'Your answer was not saved. Try again.')}};
 const reveal=async()=>{if(!practice)return;try{if(practice.presentation)await mutate('help',{presentation:practice.presentation.id});setPractice({...practice,help:true,explanation:true})}catch(e){setError(e instanceof Error?e.message:'Could not record help; explanation remains hidden.')}};
 const newNote=(block='',quote='')=>{const v=viewRef.current;if(!v)return;setNoteDraft({id:uid(),bookId:v.book.id,bookTitle:v.book.title,chapter:v.chapter,chapterTitle:v.book.chapters[v.chapter].title,block,quote,body:'',kind:'note',known:false,version:0})};
 const saveNote=async()=>{if(!noteDraft)return;try{await mutate('note',{noteId:noteDraft.id,...noteDraft});setNoteDraft(null)}catch(e){setError(e instanceof Error?e.message:'Your note could not be saved. The draft is still open.')}};
 const score=summary(state.learning,now);const due=course.concepts.map(c=>({c,due:reviewDue(state.learning,c.id)})).filter(x=>x.due!==undefined&&x.due<=now).sort((a,b)=>a.due!-b.due!)[0];const nextLesson=course.lessons.findIndex(l=>!state.learning.completed.includes(l.id));
 const completed=state.learning.completed.length;const recent=Object.entries(state.positions).sort((a,b)=>b[1].updated-a[1].updated)[0];const activeBook=recent?books.find(b=>b.id===recent[0]):undefined;
 const allBooks=[...books.map(b=>({id:b.id,title:b.title,author:b.author,kind:b.kind,chapters:b.chapters.length})),...state.books.map(b=>({...b,kind:'imported'}))];
 const filteredNotes=state.notes.filter(n=>(filter==='all'||n.kind===filter)&&[n.body,n.quote,n.bookTitle].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updated-a.updated);
 const section=foundations.sections.find(s=>s.id===foundation);
 const accountReady=!!user&&loaded;
 const readLesson=(index:number)=>void openBook(books[0],index);
 const exportData=async()=>{try{const r=await fetch('/api/export',{cache:'no-store',headers:{'X-GenBooks-Account':user?.scope??''}});if(!r.ok){const d=await r.json() as any;throw Error(d.error)}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='genbooks-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}catch(e){setError(e instanceof Error?e.message:'Export unavailable.')}};
 const importBook=async()=>{if(!importDraft)return;setImporting(true);setImportError('');try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json','X-GenBooks-Account':user?.scope??''},body:JSON.stringify({...importDraft,id:importId})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);accept(d);setImportOpen(false);setImportDraft(null);void openBook(importId,0);}catch(e){setImportError(e instanceof Error?e.message:'The book was not saved. Try again.')}finally{setImporting(false)}};
 const selectFile=async(file:File)=>{setImporting(true);setImportError('');try{setImportDraft(await parseBook(file));setImportId(uid())}catch(e){setImportError(e instanceof Error?e.message:'The file could not be read.')}finally{setImporting(false)}};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();for(const tool of [{name:'list_genbooks_readings',description:'List the public Physics readings. This does not mark them read.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>course.lessons.map(l=>({id:l.id,title:l.title}))},{name:'open_genbooks_reading',description:'Open a Physics reading. For a signed-in reader this records teaching exposure; it awards no points.',inputSchema:{type:'object',properties:{lessonId:{type:'string'}},required:['lessonId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{lessonId:string})=>{const index=course.lessons.findIndex(l=>l.id===input?.lessonId);if(index<0)throw Error('Unknown reading.');if(!await openBook(books[0],index))throw Error('The reading could not be opened and saved.');return {opened:course.lessons[index].id}}}]){try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}}return()=>life.abort()},[openBook]);
 return <div className="shell"><header className="topbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();closeReader();setTab('library')}}><BookOpen/>GenBooks</a><div className="account">{user?<><span className="sync-state" aria-live="polite">{busy?<><LoaderCircle className="spin"/>Saving</>:error?<><CloudOff/>Sync issue</>:synced?<><Cloud/>Saved</>:<><CloudOff/>Not synced</>}</span><button className="icon-button" aria-label="Settings" onClick={()=>setSettings(true)}><Settings2/></button></>:<><a className="action" href={signIn} target="_top">Sign in to sync</a><button className="icon-button" aria-label="Settings" onClick={()=>setSettings(true)}><Settings2/></button></>}</div></header>
 {error&&<div className="error-banner" role="alert"><span>{error}</span>{user&&<button className="quietlink" onClick={()=>void refresh()}>Refresh</button>}<button className="icon-button" aria-label="Dismiss message" onClick={()=>setError('')}><X/></button></div>}
 <main className={'workspace '+(view?'reading-workspace':'')}>
 {view?<><div className="reader-toolbar"><Action onClick={closeReader}><ChevronLeft/>Library</Action><button className="chapter-button" onClick={()=>setToc(true)}>Chapter {view.chapter+1} of {view.book.chapters.length}<ChevronRight/></button><div className="toolbar-right"><button className="icon-button" aria-label="Reading appearance" onClick={()=>setSettings(true)}><Text/></button>{user&&<button className="icon-button" aria-label="Write a note" onClick={()=>newNote()}><NotebookPen/></button>}</div></div><article className="reader"><p className="eyebrow">{view.book.kind==='physics'?'Physics foundations':view.book.title}</p><h1>{view.book.chapters[view.chapter].title}</h1>{view.book.kind==='physics'&&<p className="opening">{course.lessons[view.chapter].openingQuestion}</p>}
 <div className="prose" style={{fontSize:fontSize+'px'}}>{view.book.chapters[view.chapter].blocks.map(b=><div key={b.id} id={'block-'+b.id} className={'reading-block '+(b.kind==='callout'?'callout':'')} data-reading-block={b.id}>{b.kind==='heading'?<h2>{b.text}</h2>:<p>{b.text}</p>}{user&&b.kind!=='heading'&&<button className="passage-save" aria-label={'Save passage: '+b.text.slice(0,55)} onClick={()=>newNote(b.id,b.text)}><Bookmark/></button>}</div>)}</div>
 {view.book.kind==='physics'?<div className="reading-end glass"><p className="eyebrow">A moment to make it yours</p><h2>{course.lessons[view.chapter].reflectionPrompt}</h2>{finish===course.lessons[view.chapter].id?<><p className="success-line"><CheckCircle2/>Reading saved. This records participation, not mastery.</p><div className="button-row"><Action primary disabled={busy} onClick={()=>void startPractice(course.lessons[view.chapter].checks[0].conceptId,course.lessons[view.chapter].checks[0].id,false)}>Try an optional question</Action>{view.chapter<5&&<Action disabled={busy} onClick={()=>readLesson(view.chapter+1)}>Next reading</Action>}</div><p className="field-label">How did this reading feel?</p><div className="button-row feedback">{[['enjoyable','Enjoyable'],['neutral','Okay'],['tooDemanding','Too demanding']].map(([value,label])=><Action key={value} disabled={busy} onClick={()=>void attempt(async()=>{await mutate('feedback',{lesson:course.lessons[view.chapter].id,experience:value});setFinish(null)})}>{label}</Action>)}</div></>:user?<Action primary disabled={busy||!loaded} onClick={()=>void attempt(async()=>{const id=course.lessons[view.chapter].id;await mutate('finish',{lesson:id});setFinish(id)})}>Finish reading</Action>:<><p className="muted">Sign in to keep your reading and practice evidence across browsers.</p><a className="action primary" href={signIn} target="_top">Sign in to save progress</a></>}</div>:<div className="reading-end glass"><h2>Keep what matters.</h2><p className="muted">Save a passage or write a reflection in your notebook.</p>{user?<Action onClick={()=>newNote()}><NotebookPen/>Write a note</Action>:<a className="action primary" href={signIn} target="_top">Sign in to keep notes</a>}</div>}
 <div className="chapter-navigation"><Action disabled={view.chapter===0||busy} onClick={()=>void openBook(view.book,view.chapter-1)}>Previous chapter</Action><Action disabled={view.chapter===view.book.chapters.length-1||busy} onClick={()=>void openBook(view.book,view.chapter+1)}>Next chapter</Action></div><div className="source-note">{view.book.kind==='physics'?course.authorship:view.book.description}{view.book.kind==='physics'&&<button className="quietlink" onClick={()=>setSources(true)}>Read the sources</button>}</div></article></>:<Tabs value={tab} onValueChange={setTab}><TabsList className="navtabs"><TabsTrigger value="library"><Library/>Library</TabsTrigger><TabsTrigger value="learning"><FlaskConical/>Learning</TabsTrigger><TabsTrigger value="notebook"><NotebookPen/>Notebook</TabsTrigger></TabsList>
 <TabsContent value="library"><div className="pagehead"><div><h1>Your library</h1><p className="muted">Good ideas deserve a second look.</p></div><Action disabled={busy} onClick={()=>setImportOpen(true)}><Plus/>Add a book</Action></div>
 <section className="featured glass"><img className="cover" src={cover(activeBook?.kind??(recent?'imported':'physics'))} alt=""/><div><p className="eyebrow">{recent?'Pick up where you left off':'Begin with Physics'}</p><h2>{activeBook?.title??(recent?state.books.find(b=>b.id===recent[0])?.title:undefined)??course.title}</h2><p className="muted">{recent?`Chapter ${recent[1].chapter+1} · saved ${date(recent[1].updated)}`:course.subtitle}</p><Action primary disabled={!!user&&!loaded||busy} onClick={()=>void openBook(recent?recent[0]:books[0])}><BookOpen/>{recent?'Continue reading':'Start reading'}</Action></div></section>
 <div className="sectionhead"><h2>On your shelf</h2><span className="muted">{allBooks.length} books</span></div><div className="bookshelf">{allBooks.map(b=><button className="bookcard glass" key={b.id} disabled={busy||!!user&&!loaded} onClick={()=>void openBook(b.id)}><img className="cover" src={cover(b.kind)} alt=""/><div><p className="eyebrow">{b.kind==='physics'?'Physics · six readings':b.kind==='sample'?'Original sample':'Your import'}</p><h3>{b.title}</h3><p className="muted">{b.author} · {b.chapters} chapters</p>{state.positions[b.id]&&<p className="book-progress">Chapter {state.positions[b.id].chapter+1}</p>}</div></button>)}</div></TabsContent>
 <TabsContent value="learning"><div className="pagehead"><div><h1>Make it stay.</h1><p className="muted">Read a little. Return to the idea. Try it yourself.</p></div><button className="quietlink" onClick={()=>setFoundation('index')}>Why this works this way</button></div><div className="learning-top"><section className="next-card glass"><p className="eyebrow">Your next step</p><h2>{due?`Revisit ${due.c.title.toLowerCase()}`:course.lessons[nextLesson<0?0:nextLesson].title}</h2><p className="muted">{due?'Try a question before rereading. It is always okay to use help.':nextLesson<0?'You have finished all six readings. Return to an idea or explore your concepts.':'A short reading, one concrete idea, room to think.'}</p><Action primary disabled={busy||!!user&&!loaded} onClick={()=>due?void startPractice(due.c.id):readLesson(nextLesson<0?0:nextLesson)}>{due?'Review concept':'Read'}</Action></section><button className="score-card glass" onClick={()=>setScoreOpen(true)}><p className="eyebrow">Physics check score</p><div className="score-value">{score.checked?score.points:<span className="not-checked">Not checked<br/>yet</span>}{score.checked>0&&<span>/100</span>}</div><p className="muted">{score.checked?`${score.checked} of 10 checks have evidence`:'Later answers build the evidence.'}</p><span className="score-link">See how it works <Info size={16}/></span></button></div>
 <div className="sectionhead"><h2>Readings</h2><span className="muted">{completed} of 6 finished</span></div><div className="lessonlist">{course.lessons.map((l,i)=><button className="lessonrow glass" key={l.id} disabled={busy||!!user&&!loaded} onClick={()=>readLesson(i)}><span className="lessonnum">0{i+1}</span><div><h3>{l.title}</h3><p className="muted">{l.openingQuestion}</p></div>{state.learning.completed.includes(l.id)?<CheckCircle2 className="lesson-status" aria-label="Finished"/>:<span className="reading-time">{Math.max(1,Math.round(l.wordCountReading/200))} min</span>}</button>)}</div>
 <div className="sectionhead concepts-head"><h2>Your concepts</h2><button className="quietlink" onClick={()=>setSources(true)}>Sources</button></div><div className="concept-grid">{course.concepts.map(c=>{const counts=score.slots.filter(s=>s.concept===c.id&&s.status!=='unknown').length;return <section className="concept-card glass" key={c.id}><h3>{c.title}</h3><p className="muted">{c.objective}</p><p className="concept-evidence">{counts}/2 checks recorded{state.learning.learned[c.id]?' · marked learned':''}</p><div className="button-row"><Action disabled={busy||!!user&&!loaded} onClick={()=>void startPractice(c.id)}>Practice</Action>{user&&!state.learning.learned[c.id]&&<button className="quietlink" disabled={busy} onClick={()=>void attempt(()=>mutate('learned',{concept:c.id}))}>Mark learned</button>}</div></section>})}</div><p className="fine-print">“Learned” is your own label and adds no points. The score records answers to ten specific questions, not all your knowledge or skill.</p></TabsContent>
 <TabsContent value="notebook"><div className="pagehead"><div><h1>Your notebook</h1><p className="muted">The passages, words and thoughts worth keeping.</p></div></div><div className="notebook-tools"><label className="searchbox"><Search/><span className="sr-only">Search your notebook</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a passage or thought"/></label><Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs"><TabsTrigger value="all">All</TabsTrigger><TabsTrigger value="note">Notes</TabsTrigger><TabsTrigger value="word">Words</TabsTrigger></TabsList></Tabs></div>{!filteredNotes.length?<div className="glass empty"><NotebookPen/><h2>{query?'No matching notes':'Keep the ideas you want to return to.'}</h2><p className="muted">{query?'Try another word or clear your search.':'Use the bookmark beside a passage, or write a note while reading.'}</p>{!user&&<a className="action primary" href={signIn} target="_top">Sign in to save notes</a>}</div>:<div className="notes-grid">{filteredNotes.map(n=><article className="note-card glass" key={n.id}><p className="eyebrow">{n.kind==='word'?'Word':'Note'} · {date(n.updated)}</p>{n.quote&&<blockquote>{n.quote}</blockquote>}{n.body&&<p className="note-body">{n.body}</p>}<button className="note-source quietlink" onClick={()=>void openBook(n.bookId,n.chapter,n.block)}>{n.bookTitle} · {n.chapterTitle}</button><div className="note-actions"><button className="quietlink" onClick={()=>setNoteDraft({...n})}>Edit</button><button className="icon-button" aria-label={'Delete note from '+n.bookTitle} onClick={()=>setDeleteNote(n)}><Trash2/></button></div></article>)}</div>}</TabsContent></Tabs>}
 {!user&&!view&&<p className="sync-banner">Read freely. Sign in with ChatGPT to save your place and sync across browsers.</p>}{user&&!loaded&&<p role="status" className="sync-banner">Loading your saved library…</p>}
 <footer className="footer"><button className="footer-mission" onClick={()=>setFoundation('index')}>Increase retained knowledge and skills.</button><div><a href="https://github.com/jarvis-pd21/GenBooks" target="_blank" rel="noreferrer">Open source</a><button onClick={()=>setFoundation('privacy')}>Privacy</button></div></footer></main>
 <Modal open={settings} onClose={()=>setSettings(false)} title="Settings" description="A comfortable place to keep learning."><div className="settings-row"><div><h3>Dark appearance</h3><p className="muted">Saved in this browser.</p></div><Switch checked={theme==='dark'} onCheckedChange={v=>setTheme(v?'dark':'light')} aria-label="Dark appearance"/></div><div className="settings-section"><label className="field-label" htmlFor="reading-size">Reading size · {fontSize}px</label><Slider id="reading-size" min={18} max={30} step={1} value={[fontSize]} onValueChange={v=>setFontSize(v[0])} aria-label="Reading text size"/><p className="font-preview" style={{fontSize}}>Read at your own pace.</p></div>{user&&<div className="settings-section"><p className="field-label">A comfortable session</p><div className="button-row">{[5,10,20].map(n=><Action key={n} primary={state.preferences.sessionMinutes===n} disabled={busy||!loaded} onClick={()=>void attempt(()=>mutate('preferences',{minutes:n}))}>{n} minutes</Action>)}</div><p className="muted fine-print">Saved with your account. This first version does not yet adjust lessons to this preference.</p></div>}<button className="settings-link" onClick={()=>{setSettings(false);setFoundation('index')}}><BookOpen/><div><h3>Foundations</h3><p className="muted">Our mission, definitions and learning science</p></div><ChevronRight/></button><button className="settings-link" onClick={()=>{setSettings(false);setFoundation('privacy')}}><Info/><div><h3>Your data and privacy</h3><p className="muted">What syncs, where it lives and current limits</p></div><ChevronRight/></button>{user?<div className="settings-section"><p className="muted account-name">Signed in as {user.name}</p><div className="button-row"><Action onClick={()=>void exportData()}><Download/>Export my data</Action><a className="action" href={signOut} target="_top">Sign out</a></div></div>:<a className="action primary" href={signIn} target="_top">Sign in with ChatGPT</a>}</Modal>
 <Modal open={foundation!==null} onClose={()=>setFoundation(null)} title={foundation==='index'?'Foundations':foundation==='privacy'?'Your data and privacy':section?.title??'Foundations'} wide>{foundation==='index'?<div className="foundations-content"><p className="eyebrow">Our mission</p><h2 className="mission">{foundations.mission}</h2><p>{foundations.vision}</p><div className="foundation-list">{foundations.sections.map(s=><button key={s.id} onClick={()=>setFoundation(s.id)}><div><h3>{s.title}</h3><p className="muted">{s.summary}</p></div><ChevronRight/></button>)}</div><button className="quietlink" onClick={()=>setFoundation('privacy')}>Web app privacy and sync</button></div>:foundation==='privacy'?<div className="foundations-content"><p>Sign-in uses your ChatGPT account. Your imported text, notes, reading positions and Physics evidence are stored in your account on the hosted service and sync across browsers signed into that same account.</p><p>Records are private to your account; they are not end-to-end encrypted. The service operator and hosting provider can technically access stored data. Do not import sensitive material you do not want stored there.</p><p>We do not add advertising trackers or send your books to an AI provider. Public source code does not include your saved library. Appearance settings stay in each browser.</p><p>The native iPhone app currently keeps its own data. It does not sync with this web account. Sign-in and sync require an internet connection; this web release is not a fully offline app.</p><p>Use Settings → Export my data for a copy of your account records and imported book text. Imports currently allow 40 books, 8 MB per input file, up to 100 chapters and 1.5 MB of extracted text per book. Notes support up to 1,000 entries. Imported layout and images are not retained.</p><p>For account-data deletion or a privacy issue, contact <a href="mailto:jarvis@agi-jarvis.com">jarvis@agi-jarvis.com</a>.</p></div>:section?<div className="foundations-content"><button className="quietlink" onClick={()=>setFoundation('index')}>All foundations</button>{section.paragraphs.map((p,i)=><p key={i}>{p}</p>)}{section.bullets.length>0&&<ul>{section.bullets.map((b,i)=><li key={i}>{b}</li>)}</ul>}{section.references.length>0&&<div className="reference-list"><h3>Further reading</h3>{section.references.map(r=><a key={r.url} href={r.url} target="_blank" rel="noreferrer">{r.title}<ExternalLink size={15}/></a>)}</div>}</div>:null}</Modal>
 <Modal open={toc} onClose={()=>setToc(false)} title="Contents" description={view?.book.title}>{view&&<div className="toc-list">{view.book.chapters.map((c,i)=><button key={c.id} disabled={busy} className={view.chapter===i?'current':''} onClick={()=>void openBook(view.book,i)}><span>{i+1}</span>{c.title}{view.chapter===i&&<BookOpen size={16}/>}</button>)}</div>}</Modal>
 <Modal open={scoreOpen} onClose={()=>setScoreOpen(false)} title="Physics check score" description="Ten specific questions. Every point has a record." wide><div className="score-explanation"><div className="score-large">{score.points}<span>/100</span></div><p>Each question contributes 10 points when its latest eligible answer is correct, or 0 when it is incorrect. Unchecked questions contribute 0 and remain labeled unchecked.</p><p>Reading, explanations and marking a concept learned add no points. A wrong eligible answer can remove 10 previously earned points. Time alone never removes points.</p><p>For a question to count: use a concept review, wait at least 24 hours after relevant teaching or a counted check, wait seven days after seeing that same question, and answer without help. Opening more material for that concept after the question starts makes it practice only.</p><p className="muted">These intervals are product rules, not scientifically optimal timings. This small question set cannot measure all retained knowledge or skills.</p><div className="score-slots">{score.slots.map(s=><div key={s.question}><div><h3>{course.concepts.find(c=>c.id===s.concept)?.title}</h3><p className="muted">{questions.find(q=>q.id===s.question)?.prompt}</p><p className="fine-print">{s.status==='unknown'?'Not checked':(s.status==='correct'?'Correct':'Incorrect')+' · '+date(s.at!)+(s.older?' · evidence older than 14 days':'')}</p></div><strong>{s.points}</strong></div>)}</div>{state.learning.receipts.length>0&&<div className="receipt-list"><h3>Recent answer evidence</h3>{state.learning.receipts.slice(-8).reverse().map(r=><div key={r.id}><p><strong>{r.correct?'Correct':'Incorrect'}</strong> · {r.counted?'counted check':'practice'} · {dateTime(r.at)}</p><p className="muted">{r.reason}</p><span>{r.delta>0?'+':''}{r.delta} points</span></div>)}</div>}</div></Modal>
 <Modal open={sources} onClose={()=>setSources(false)} title="Sources for Physics" description={course.authorship} wide><div className="reference-list">{course.sources.map(s=><article key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={15}/></a><p>{s.supports}</p><p className="fine-print muted">{s.rights}</p></article>)}</div></Modal>
 <Modal open={practice!==null} onClose={()=>setPractice(null)} title={practice?.receipt?'Your answer':'A fresh look'} description={practice?.presentation?.eligibility.canCount?'Eligible for your check score':'Practice only'} wide>{practice&&<div className="practice"><p className="question-prompt">{practice.question.prompt}</p><RadioGroup value={practice.choice} onValueChange={v=>setPractice({...practice,choice:v})} disabled={!!practice.receipt||busy} className="choices" aria-label="Choose your answer">{practice.question.choices.map(c=><label key={c.id} className={'choice '+(practice.choice===c.id?'selected':'')} htmlFor={'choice-'+c.id}><RadioGroupItem value={c.id} id={'choice-'+c.id}/><span>{c.text}</span></label>)}</RadioGroup>{practice.receipt?<div className={'answer-result '+(practice.receipt.correct?'correct':'incorrect')} role="status"><h3>{practice.receipt.correct?'That’s right.':'Not quite.'} {practice.receipt.delta!==0&&<span>{practice.receipt.delta>0?'+':''}{practice.receipt.delta} points</span>}</h3><p>{practice.question.explanation}</p><p className="fine-print">{practice.receipt.reason}</p><Action onClick={()=>setPractice(null)}>Done</Action></div>:<><div className="help-choice"><Switch id="used-help" checked={practice.help} onCheckedChange={v=>setPractice({...practice,help:v})} disabled={busy||practice.explanation}/><label htmlFor="used-help">I used help, notes or another tool</label></div><div className="button-row"><Action primary disabled={!practice.choice||busy} onClick={()=>void saveAnswer()}>{user?'Save my answer':'Check my answer'}</Action><button className="quietlink" disabled={busy} onClick={()=>void reveal()}>Show explanation</button><button className="quietlink" onClick={()=>setPractice(null)}>Skip</button></div>{practice.explanation&&<div className="explanation"><p>{practice.question.explanation}</p><p className="fine-print">Help recorded. This answer will be practice only.</p></div>}<p className="eligibility">{practice.presentation?.eligibility.reason??'Preview only. Sign in to keep evidence and use delayed checks.'}{practice.presentation?.eligibility.nextEligibleAt&&<> Earliest possible: {dateTime(practice.presentation.eligibility.nextEligibleAt)}; further teaching or question exposure can move this time.</>}</p></>}</div>}</Modal>
 <Modal open={noteDraft!==null} onClose={()=>setNoteDraft(null)} title={noteDraft?.version?'Edit note':'Keep this idea'} description={noteDraft?.chapterTitle}>{noteDraft&&<form onSubmit={e=>{e.preventDefault();void saveNote()}} className="note-form">{noteDraft.quote&&<blockquote>{noteDraft.quote}</blockquote>}<label className="field-label" htmlFor="note-body">Your thought</label><textarea id="note-body" disabled={busy} value={noteDraft.body} onChange={e=>setNoteDraft({...noteDraft,body:e.target.value})} rows={5} maxLength={10000} placeholder="What does this connect to?" autoFocus/><div className="help-choice"><Switch id="save-word" disabled={busy} checked={noteDraft.kind==='word'} onCheckedChange={v=>setNoteDraft({...noteDraft,kind:v?'word':'note'})}/><label htmlFor="save-word">Keep this in Words</label></div><Action type="submit" primary disabled={busy||!noteDraft.body.trim()&&!noteDraft.quote}>Save note</Action></form>}</Modal>
 <AlertDialog open={!!deleteNote} onOpenChange={v=>!v&&setDeleteNote(null)}><AlertDialogContent className="app-dialog"><AlertDialogHeader><AlertDialogTitle>Delete this note?</AlertDialogTitle><AlertDialogDescription>This removes the note from your synced notebook. The book stays in your library.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep note</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void attempt(async()=>{await mutate('delete-note',{noteId:deleteNote!.id,version:deleteNote!.version});setDeleteNote(null)})}}>Delete note</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Modal open={importOpen} onClose={()=>!importing&&setImportOpen(false)} title="Add a book" description="Your imported books are private to your signed-in account.">{!user?<div className="import-content"><p>Bring a DRM-free EPUB, plain text or Markdown file. Sign in to keep it in your library across browsers.</p><a className="action primary" href={signIn} target="_top">Sign in with ChatGPT</a></div>:<div className="import-content"><label className="file-drop"><BookMarked/><strong>{importing?'Reading your file…':'Choose an EPUB or text file'}</strong><span className="muted">.epub, .txt, .md · up to 8 MB</span><input type="file" accept=".epub,.txt,.md" disabled={importing} onChange={e=>{const f=e.target.files?.[0];if(f)void selectFile(f)}}/></label><p className="fine-print muted">Text import keeps words and chapters. Images, original layout and equation formatting may be lost. No protected books, PDF or scanned-page import in this web release. Up to 40 books, 100 chapters and 1.5 MB extracted text per book.</p>{importError&&<p role="alert" className="inline-error">{importError}</p>}{importDraft&&<><label className="field-label" htmlFor="book-title">Title</label><input id="book-title" className="text-input" value={importDraft.title} maxLength={200} onChange={e=>setImportDraft({...importDraft,title:e.target.value})}/><label className="field-label" htmlFor="book-author">Author</label><input id="book-author" className="text-input" value={importDraft.author} maxLength={200} onChange={e=>setImportDraft({...importDraft,author:e.target.value})}/><p className="muted">{importDraft.chapters.length} chapters ready</p><Action primary disabled={importing||!importDraft.title.trim()} onClick={()=>void importBook()}>{importing?'Saving…':'Add to my library'}</Action></>}</div>}</Modal>
 </div>
}
