import {json,user,input,failure,id,text,ApiError} from '@/lib/api';
import {loadState,mutateState,bucket} from '@/lib/store';
import type {Book} from '@/lib/models';
export const dynamic='force-dynamic';
export async function POST(request:Request){try{const owner=await user(request);const data=await input(request,2_000_000);const bookId=id(data.id);if(['physics','argentina'].includes(bookId))throw new ApiError('Choose a new book identifier.');const {state,revision}=await loadState(owner);const existing=state.books.find(b=>b.id===bookId);if(existing)return json({state,revision,account:owner,result:{id:bookId},serverTime:Date.now()});if(state.books.length>=40)throw new ApiError('The current limit is 40 imported books per account.');if(!Array.isArray(data.chapters)||data.chapters.length<1||data.chapters.length>100)throw new ApiError('Import 1–100 chapters.');
 const chapters=data.chapters.map((c:Record<string,unknown>,i:number)=>{if(!Array.isArray(c.blocks)||c.blocks.length>1000)throw new ApiError('A chapter has too many paragraphs.');return {id:bookId+':'+i,title:text(c.title,200),blocks:c.blocks.map((b:Record<string,unknown>,j:number)=>({id:bookId+':'+i+':'+j,kind:b.kind==='heading'?'heading':'paragraph',text:text(b.text,30000)}))};});if(chapters.some((c:{blocks:unknown[]})=>!c.blocks.length))throw new ApiError('Each chapter needs readable text.');
 const book:Book={id:bookId,title:text(data.title,200),author:text(data.author||'Imported by you',200),description:'Your private text import. Original layout, illustrations and equation formatting may differ.',kind:'imported',chapters};const payload=JSON.stringify(book);if(new TextEncoder().encode(payload).length>1_500_000)throw new ApiError('The extracted book text exceeds 1.5 MB. Import a shorter section.');
 const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(owner));const scope=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');const contentDigest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(payload));const contentHash=Array.from(new Uint8Array(contentDigest)).map(b=>b.toString(16).padStart(2,'0')).join('');const key='books/'+scope+'/'+bookId+'/'+contentHash+'.json';
 await bucket().put(key,payload,{httpMetadata:{contentType:'application/json'}});
 const result=await mutateState(owner,s=>{if(s.books.some(b=>b.id===bookId))return {id:bookId};if(s.books.length>=40)throw new ApiError('The current limit is 40 imported books per account.');s.books.push({id:bookId,title:book.title,author:book.author,chapters:chapters.length,key,added:Date.now(),bytes:new TextEncoder().encode(payload).length});return {id:bookId};});return json({...result,account:owner,serverTime:Date.now()});}catch(e){return failure(e)}}
